### ISSUE TITLE
contributor guidelines

### ISSUE THREAD

**Issue by soodoku** [GaryBAYLOR/mixR#17]
JOSS expects community guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines

check this out: https://www.contributor-covenant.org/version/1/0/0/code-of-conduct/

here's how i link to it in my readme: https://github.com/soodoku/tuber#contributor-code-of-conduct

**Comment by GaryBAYLOR** [comment]
@soodoku Thanks for the information. I have added this section in README.md
