### ISSUE TITLE
statement of need within readme/documentation

### ISSUE THREAD

**Issue by soodoku** [GaryBAYLOR/mixR#18]
I think you have an ok starting point around 'statement of need' in your paper but we JOSS also evaluates if you provide that in your documentation for the software. 

I recommend adding a crisp #knowwhy in your readme to orient the users and help guide them to other places if there needs are different.

**Comment by GaryBAYLOR** [comment]
Hi @soodoku Thanks for the comment. I have added a _Why mixR ?_ section at the beginning of README.md. Please let me know if it looks good to you or needs further improvement.
