### ISSUE TITLE
model object

### ISSUE THREAD

**Issue by soodoku** [GaryBAYLOR/mixR#20]
hey trying some of the code in the readme

```
# Selecting the best g for Normal mixture model
s_normal = select(x2, ncomp = 2:6)
```
It prints out: "The final model: normal mixture (equal variance) with 4 components"

I did
```
str(s_normal)
```
```
List of 5
 $ ncomp    : int [1:10] 2 2 3 3 4 4 5 5 6 6
 $ equal.var: chr [1:10] "Y" "N" "Y" "N" ...
 $ bic      : num [1:10] -387 -387 -403 -443 -445 ...
 $ best     : chr [1:10] " " " " " " " " ...
 $ family   : chr "normal"
 - attr(*, "class")= chr "selectEM"
```

I typed 
```s_normal$best
 [1] " " " " " " " " "*" " " " " " " " " " "
```

Is that expected? Why?

**Comment by GaryBAYLOR** [comment]
Hi @soodoku Thanks for the question. The object of `s_normal` is supposed to be viewed in tabular format shown as below but not extracted independently. I put each column of the table as separate list items so `s_normal$best` is only meaning when the whole `s_normal` is printed. But this is a place I can improve to avoid confusion (to store the table as a whole list item). 
```r
> s_normal
   ncomp equal.var      bic best
1      2         Y 4309.223     
2      2         N 4238.221    *
3      3         Y 4323.038     
4      3         N 4256.698     
5      4         Y 4272.660     
6      4         N 4275.925     
7      5         Y 4264.199     
8      5         N 4291.169     
9      6         Y 4278.018     
10     6         N 4311.364     
```
Does this make sense to you? If so I can go ahead and make this change to the function definition of `select` and the corresponding function description in the manual.
