### ISSUE TITLE
has bic been consistently implemented?

### ISSUE THREAD

**Issue by soodoku** [GaryBAYLOR/mixR#21]
when i do

```
mod1 = mixfit(x1, ncomp = 2)
```

```
mod1$bic
[1] 4238.221
```

with 

```
s_normal = select(x2, ncomp = 2:6)
```

````
s_normal$bic
 [1] -386.7280 -387.1504 -403.0483 -443.2730 -445.2417 -440.1219 -431.4261 -426.6852 -440.6210 -408.1540
```

**Comment by GaryBAYLOR** [comment]
Hi @soodoku, the BIC is consistently implemented. The reason you see different BIC values is because `mixfit` and `select` returns objects of different classes. `select` is not designed to return the same object as `mixfit` as the former is to compare and visualize candidate models using BIC.
```r
> class(mod1)
[1] "mixfitEM"
> class(s_normal)
[1] "selectEM"
```
`mod1$bic` returns the BIC of the fitted model (scalar), and `s_normal$bic` returns a vector of BIC values for the mixture models fitted and compared with different `ncomp`. In the above example,  when running `select(x2, ncomp = 2:6)`, what happed behind the stage is ten Gaussian mixture models are fitted (ncomp = 2, 3, 4, 5, 6 and for each ncomp, two GMMs are fitted with equal variance and unequal variances).

Actually, if you run `select(x1, ncomp = 2:6)` you will see the second row contains BIC that is the same as `mod1$bic` 
```r
> s_normal = select(x1, ncomp = 2:6)
The final model: normal mixture (unequal variances) with 2 components
> s_normal
   ncomp equal.var      bic best
1      2         Y 4309.223     
2      2         N 4238.221    *
3      3         Y 4323.038     
4      3         N 4256.698     
5      4         Y 4272.660     
6      4         N 4275.925     
7      5         Y 4264.199     
8      5         N 4291.169     
9      6         Y 4278.018     
10     6         N 4311.364     
```
Hope this helps!

**Comment by soodoku** [comment]
Hey, not talking about scalar vs. vector but large positive vs. large
negative.

**Comment by GaryBAYLOR** [comment]
Hi @soodoku, BIC could be positive or negative depending on the data and model complexity.

I followed the definition of BIC to implement it in the package: BIC = k * log(n) - 2 * log(L), in whcih k is the total number of parameters in the model, n is the size of data, and log(L) is the log-likelihood (see [Wikipage](https://en.wikipedia.org/wiki/Bayesian_information_criterion) reference).

My implementation is [here](https://github.com/GaryBAYLOR/mixR/blob/e1a0b8c6dede01b9d8f64b74f8f0bfe84ab6c32f/R/normalEM.R#L42), which is consistent with the [definition](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/AIC.html) in the `stats` package that comes with base R, in which it describes the definition of BIC and says that _"When comparing models fitted by maximum likelihood to the same data, the smaller the AIC or BIC, the better the fit"_.

Interestingly, some other mixture model packages have different implementation for BIC. For example, in `mclust` the BIC is the BIC defined as 2 * log(L) - k * log(n), the opposite of the usual definition. As a result, by running the following code we can see very close BIC for the best model in `mixR` and `mclust` but the values of BIC are in opposite sign. For packages like `mclust`, it would be the larger the AIC or BIC, the better the fit.
```
# library(mixR)
# library(mclust)
set.seed(102)
x1 = rmixnormal(1000, c(0.3, 0.7), c(-2, 3), c(2, 1))
x2 = rmixweibull(1000, c(0.4, 0.6), c(0.6, 1.3), c(0.1, 0.1))

mod_select_mixR_1 = select(x1, ncomp = 2:6)
mod_select_mclust_1 = mclustBIC(x1, G = 2:6)
mod_select_mixR_1
mod_select_mclust_1

mod_select_mixR_2 = select(x2, ncomp = 2:6)
mod_select_mclust_2 = mclustBIC(x2, G = 2:6)
mod_select_mixR_2
mod_select_mclust_2
```
Please let me know if I explains clearly and it makes sense to you.
Thanks!

**Comment by soodoku** [comment]
Agree on all points. I was worried, it is positive in one place and
negative in another. If all good, close the issue.

**Comment by GaryBAYLOR** [comment]
Thanks @soodoku, I am pretty confident about the implementation of BIC in `mixR` now. An extra point about why BIC is sometimes positive and some other times negative is: for continuous distributions, the likelihood is the sum of log(density) for all data points.  The density could be between 0 and 1 and close to zero (like the density for `x1`), in which case log(density) is negative, and multiple the sum by -2 would lead to a positive BIC. The density could also be well above 1 (for a lot of data points in `x2`), which may produce negative BIC when taking log transform on the density and them multiply by -2.

I will go ahead and close the issue. Thank you for bringing this up and it is an interesting discussion.
