### ISSUE TITLE
Binned data format

### ISSUE THREAD

**Issue by welch16** [GaryBAYLOR/mixR#32]
I think that the one of the main contributions of this package is that allows the user to work with binned data. However, the examples in the vignette that utilize binned data are from simulated data that was later binned using the `mixR::bin` function which may confuse an inexperienced user.

I consider that the vignette and the README file could be improved with an explicit example of the binned data matrix expected by the `mixfit` function that wasn't generated with `mixR::bin`

**Comment by GaryBAYLOR** [comment]
Hi @welch16,
I have added two examples in the vignette for fitting mixtures models with binned data which is not binned using `mixR::bin`. One is `Stamp2` data in mixR pacakge. The other one is `cassie` data from `mixdist` package. Please refer to Section 2.4 in the [vignette](https://github.com/GaryBAYLOR/mixR/blob/issue_32/vignettes/intro-to-mixr.pdf) for details.  I also updated the README.md file.

The vignette and other changes are currently in Github but will be updated to CRAN in the next release.

Please let me know it looks good to you now.

Thanks!

**Comment by welch16** [comment]
That looks great, thanks!
